// =====================
//   YAMI – App Data
// =====================

export const restaurants = [
  {
    id: 'r1',
    name: 'Flame Burger Co.',
    cuisine: 'American Burgers',
    rating: 4.8,
    reviewCount: 2341,
    deliveryTime: '18–25 min',
    deliveryFee: 1.99,
    minOrder: 10,
    distance: '0.8 mi',
    tags: ['Trending 🔥', 'Fan Favorite'],
    avatar: '🍔',
    coverColor: 'linear-gradient(135deg, #ff6b35, #ff2d78)',
  },
  {
    id: 'r2',
    name: 'Sakura Sushi Bar',
    cuisine: 'Japanese',
    rating: 4.9,
    reviewCount: 1876,
    deliveryTime: '25–35 min',
    deliveryFee: 2.99,
    minOrder: 15,
    distance: '1.2 mi',
    tags: ['Top Rated ⭐', 'Healthy'],
    avatar: '🍣',
    coverColor: 'linear-gradient(135deg, #9d4edd, #ff2d78)',
  },
  {
    id: 'r3',
    name: 'Nonna\'s Kitchen',
    cuisine: 'Italian Pasta',
    rating: 4.7,
    reviewCount: 3102,
    deliveryTime: '20–30 min',
    deliveryFee: 0,
    minOrder: 12,
    distance: '0.5 mi',
    tags: ['Free Delivery 🎉', 'Comfort Food'],
    avatar: '🍝',
    coverColor: 'linear-gradient(135deg, #ff6b35, #ffd60a)',
  },
  {
    id: 'r4',
    name: 'Seoul Kitchen',
    cuisine: 'Korean BBQ',
    rating: 4.6,
    reviewCount: 987,
    deliveryTime: '30–40 min',
    deliveryFee: 1.49,
    minOrder: 20,
    distance: '2.1 mi',
    tags: ['New 🆕', 'Spicy 🌶️'],
    avatar: '🥩',
    coverColor: 'linear-gradient(135deg, #ff2d78, #9d4edd)',
  },
];

export const reels = [
  {
    id: 'v1',
    restaurantId: 'r1',
    restaurantName: 'Flame Burger Co.',
    image: '/food_reel_1.png',
    dish: 'Smash Burger Stack',
    description: 'Double smash patties, secret sauce, caramelized onions, aged cheddar 🔥',
    price: 14.99,
    originalPrice: null,
    likes: 48200,
    comments: 1340,
    shares: 892,
    liked: false,
    saved: false,
    tags: ['#BurgerReels', '#FoodTok', '#FlameGrilled'],
    extras: [
      { name: 'Extra Patty', price: 3.50 },
      { name: 'Bacon', price: 2.00 },
      { name: 'Truffle Fries', price: 4.99 },
    ],
  },
  {
    id: 'v2',
    restaurantId: 'r3',
    restaurantName: "Nonna's Kitchen",
    image: '/food_reel_2.png',
    dish: 'Carbonara Perfetta',
    description: 'Authentic Roman carbonara – pecorino, guanciale, farm fresh eggs, zero cream 🤌',
    price: 17.50,
    originalPrice: 21.00,
    likes: 93100,
    comments: 4220,
    shares: 2100,
    liked: false,
    saved: false,
    tags: ['#PastaLovers', '#ItalianFood', '#FoodAesthetic'],
    extras: [
      { name: 'Extra Guanciale', price: 2.50 },
      { name: 'Burrata Side', price: 5.50 },
      { name: 'Garlic Bread', price: 3.00 },
    ],
  },
  {
    id: 'v3',
    restaurantId: 'r2',
    restaurantName: 'Sakura Sushi Bar',
    image: '/food_reel_3.png',
    dish: 'Omakase Roll Platter',
    description: 'Chef\'s selection – Spicy Tuna, Dragon Roll, Rainbow Roll, Salmon Avocado 🍱',
    price: 34.99,
    originalPrice: null,
    likes: 127400,
    comments: 6800,
    shares: 4500,
    liked: false,
    saved: false,
    tags: ['#SushiTime', '#Omakase', '#JapaneseFood'],
    extras: [
      { name: 'Miso Soup', price: 2.00 },
      { name: 'Edamame', price: 3.50 },
      { name: 'Extra Wasabi Set', price: 1.00 },
    ],
  },
  {
    id: 'v4',
    restaurantId: 'r4',
    restaurantName: 'Seoul Kitchen',
    image: '/food_reel_4.png',
    dish: 'Crispy Korean Fried Chicken',
    description: 'Double-fried crispy wings, gochujang glaze, toasted sesame, kimchi slaw 🌶️',
    price: 19.99,
    originalPrice: null,
    likes: 71300,
    comments: 3100,
    shares: 1870,
    liked: false,
    saved: false,
    tags: ['#KFCVibes', '#KoreanFood', '#SpicyFood'],
    extras: [
      { name: 'Extra Sauce', price: 1.50 },
      { name: 'Kimchi', price: 3.00 },
      { name: 'Steamed Rice', price: 2.50 },
    ],
  },
];

export const formatNumber = (n) => {
  if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M';
  if (n >= 1000) return (n / 1000).toFixed(1) + 'K';
  return n.toString();
};

export const categories = [
  { id: 'all', label: 'For You', emoji: '✨' },
  { id: 'burgers', label: 'Burgers', emoji: '🍔' },
  { id: 'sushi', label: 'Sushi', emoji: '🍣' },
  { id: 'pasta', label: 'Pasta', emoji: '🍝' },
  { id: 'korean', label: 'Korean', emoji: '🥩' },
  { id: 'pizza', label: 'Pizza', emoji: '🍕' },
  { id: 'tacos', label: 'Tacos', emoji: '🌮' },
  { id: 'desserts', label: 'Desserts', emoji: '🍰' },
];
